---
## Offline install mode
offline_install: no

## kubernetes version
kube_version: 1.18.2

## kubeadm version (RPM)
kubeadm_version: "{{ kube_version }}-0"

## kubelet version (RPM)
kubelet_version: "{{ kubeadm_version }}"

## kubectl version (RPM)
kubectl_version: "{{ kubelet_version }}"

## kubeadm version (apt)
kubeadm_apt_version: "{{ kube_version }}-00"

## kubelet version (apt)
kubelet_apt_version: "{{ kubeadm_apt_version }}"

## kubectl version (apt)
kubectl_apt_version: "{{ kubelet_apt_version }}"

## Advertise address of kube-apiserver on each master nodes.
## (should be defined as host vars)
ip: "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}"

## External load balancer address and port.
#lb_apiserver_address: 1.2.3.4
lb_apiserver_address: "{{ ip }}"
lb_apiserver_port: 6443

# Pod CIDR
pod_subnet: 192.168.0.0/16

# Firewall
firewall_enabled: yes

# Proxy
proxy_url: ""
proxy_noproxy: "127.0.0.1,localhost,{{ ip }}"

proxy_env:
  http_proxy: "{{ proxy_url }}"
  https_proxy: "{{ proxy_url }}"
  no_proxy: "{{ proxy_noproxy }}"

# master schedulable?
master_schedulable: yes

is_master: no
is_worker: no
